In [2]:
import numpy as np

In [3]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arra = np.array(lista)


In [7]:
type(arra)


numpy.ndarray

In [8]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Los arreglos siempre empiezan en la posición cero

In [12]:
arra[1]

2

In [13]:
arra[0]

1

In [14]:
matriz[0]

array([1, 2, 3])

In [15]:
matriz[2]

array([7, 8, 9])

In [16]:
matriz[2,0]

7

In [17]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arra[0:2]

array([1, 2])

In [31]:
arra[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
arra[:3]

array([1, 2, 3])

In [34]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arra[::3]

array([1, 4, 7])

In [35]:
arra[-1]

9

In [36]:
arra[-3:]

array([7, 8, 9])

In [37]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])